apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  sources:
  - chart: kube-prometheus-stack
    helm:
      valueFiles: 
      - $values/applications/monitoring/values.yaml
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 77.13.0
  - repoURL: https://github.com/sharmash3/kafka-cdc-gitops.git  
    targetRevision: HEAD
    ref: values
    
  - repoURL: https://github.com/sharmash3/kafka-cdc-gitops.git  
    targetRevision: HEAD
    path: applications/monitoring/components/  
  syncPolicy:
    managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/audit: baseline
            pod-security.kubernetes.io/enforce-version: latest
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true